# explanation of data structure:
#
# ["group name", "group description", # might want to add the problem text here, too?
#   # array of sections
#   ["section name", "section description",
#     # array of bullets
#     ["bullet name", "bullet description"]
#   ]
# ]

data = [["Civil Rights",
  "**Barack Obama will combat employment discrimination:** Obama and Biden will work to overturn the Supreme Court's recent ruling that curtails s and racial minorities' ability to challenge pay discrimination. They will also pass the Fair Pay Act to ensure that women receive equal pay for equal work and the Employment Non-Discrimination Act to prohibit discrimination based on sexual orientation or gender identity or expression.women\n\n**Strengthen civil rights enforcement:** Obama and Biden will reverse the politicization that has occurred in the Bush Administration's Department of Justice. They will put an end to the ideological litmus tests used to fill positions within the Civil Rights Division.\n\n**Expand hate crime statutes:** Obama and Biden will strengthen federal hate crimes legislation, expand hate crimes protection by passing the Matthew Shepard Act, and reinvigorate enforcement at the Department of Justice's Criminal Section.",
  [["Strengthen Civil Rights Enforcement", "", []],
   ["Combat Employment Discrimination", "", []],
   ["Expand Hate Crimes Statutes", "", []],
   ["End Deceptive Voting Practices", "", []],
   ["End Racial Profiling", "", []],
   ["Reduce Crime Recidivism by Providing Ex-Offender Support", "", []],
   ["Eliminate Sentencing Disparities", "", []],
   ["Expand Use of Drug Courts", "", []]]],
 ["Defense",
  "**Barack Obama will rebuild the military for 21st century tasks:**  Obama and Biden will complete the effort to increase our ground forces by 65,000 soldiers and 27,000 Marines. They will also invest in 21st century missions like counterinsurgency by building up our special operations forces, civil affairs, information operations, foreign language training and other units and capabilities that remain in chronic short supply.\n\n**Restore the readiness of the National Guard and Reserves:** Obama and Biden will provide the National Guard with the equipment it needs for foreign and domestic emergencies. They will ensure that reservists and Guard members are treated fairly when it comes to employment, health, and education benefits.\n\n**Engage our allies in meeting our common security challenges:** Obama and Biden will renew alliances and ensure our allies contribute their fair share to our mutual security.",
  [["Invest in a 21st Century Military", "", []],
   ["Build Defense Capabilities for the 21st Century", "", []],
   ["Restore the Readiness of the National Guard and Reserves", "", []],
   ["Develop Whole of Government Initiatives to Promote Security", "", []],
   ["Restore Our Alliances", "", []],
   ["Reform Contracting", "", []]]],
 ["Disabilities",
  "**Barack Obama will provide educational opportunities to Americans with disabilities:**  Obama and Biden will fight to provide students with disabilities the public education they have a right to, invest in early intervention programs, improve college opportunities, and support universal screening of infants.\n\n**End workplace discrimination and promote equal opportunity:** Obama and Biden will restore the Americans with Disabilities Act, reducing workplace and labor market discrimination against people with disabilities.\n\n**Support independent, community-based living for Americans with disabilities:** Obama and Biden will ensure people with mental or functional disabilities are placed in community settings when appropriate.",
  []],
 ["Economy",
  "**Barack Obama will provide a tax cut for working families:** Obama and Biden will restore fairness to the tax code and provide 95 percent of working Americans the tax relief they need. They will create a new \"Making Work Pay\" tax credit of up to $500 per person, or $1,000 per working family.\n\n**Provide tax relief for small businesses and startups:** Obama and Biden will eliminate all capital gains taxes on startup and small businesses to encourage innovation and job creation.\n\n**Fight for fair trade:** Obama and Biden will fight for a trade policy that opens up foreign markets to support good American jobs. They will use trade agreements to spread good labor and environmental standards around the world.",
  [["Jumpstart the Economy", "", []],
   ["Provide Middle Class Americans Tax Relief", "", []],
   ["Trade", "", []],
   ["Job Creation", "", []],
   ["Support Small Business", "", []],
   ["Labor", "", []],
   ["Protect Homeownership and Crack Down on Mortgage Fraud", "", []],
   ["Address Predatory Credit Card Practices", "", []],
   ["Reform Bankruptcy Laws", "", []],
   ["Work/Family Balance", "", []]]],
 ["Education",
  "**Barack Obama will reform No Child Left Behind:** Obama and Biden believe teachers should not be forced to spend the academic year preparing students to fill in bubbles on standardized tests and he will improve the assessments used to track student progress to measure readiness for college.\n\n**Invest in early childhood education:** The Obama-Biden comprehensive \"Zero to Five\" plan will provide critical support to young children and their parents. And they will help states move toward voluntary, universal pre-school.\n\n**Make college affordable to all Americans:** Obama and Biden will create a new American Opportunity Tax Credit worth $4,000 in exchange for community service. It will cover two-thirds the cost of tuition at the average public college or university and make community college tuition completely free for most students.",
  [["Early Childhood Education", "", []],
   ["K-12", "", []],
   ["Recruit, Prepare, Retain, and Reward Teachers", "", []],
   ["Higher Education", "", []]]],
 ["Energy & Environment", "", []],
 ["Ethics",
  "**Barack Obama will centralize ethics and lobbying information for voters:** Obama and Biden will create a centralized Internet database of lobbying reports, ethics records, and campaign finance filings.\n\n**Require independent monitoring of lobbying laws and ethics rules:** Obama and Biden will fight for an independent watchdog agency to oversee the investigation of congressional ethics violations.\n\n**Close the revolving door on former and future employers:** No political appointees in an Obama-Biden administration will be permitted to work on regulations or contracts directly and substantially related to their prior employer for two years. And no political appointee will be able to lobby the executive branch after leaving government service during the remainder of the administration.",
  [["Shine the Light on Washington Lobbying", "", []],
   ["Shine the Light on Federal Contracts, Tax Breaks and Earmarks", "", []],
   ["Bring Americans Back into their Government", "", []],
   ["Free the Executive Branch from Special Interest Influence", "", []]]],
 ["Faith",
  "*\"(Obama's speech on faith) may be the most important pronouncement by a Democrat on faith and politics since John F. Kennedy's Houston speech in 1960 declaring his independence from the Vatican...Obama offers the first faith testimony I have heard from any politician that speaks honestly about the uncertainties of belief.\"*\n&em; E.J. Dionne, Op-Ed., Washington Post, June 30, 2006\n\nIn June of 2006, Senator Obama delivered what was called the most important speech on religion and politics in 40 years. Speaking before an evangelical audience, Senator Obama candidly discussed his own religious conversion and doubts, and the need for a deeper, more substantive discussion about the role of faith in American life.\nSenator Obama also laid down principles for how to discuss faith in a pluralistic society, including the need for religious people to translate their concerns into universal, rather than religion-specific, values during public debate. In December, 2006, Senator Obama discussed the importance of faith in the global battle against AIDS.",
  []],
 ["Family",
  "**Barack Obama will provide a \"Making Work Pay\" tax cut for America's working families:** Obama and Biden will restore fairness to the tax code and 95 percent of workers the tax relief they need. They will create a new \"Making Work Pay\" tax credit of up to $500 per person, or $1,000 per working family.\n\n**Strengthen fatherhood and families:** Obama and Biden will work to remove some of the government penalties on married families, crack down on men avoiding child support payments, fund support services for fathers and their families, and support domestic violence prevention efforts.\n\n**Restore Work-Family Balance:** Obama and Biden will double funding for after-school programs, expand the Family Medical Leave Act, provide low-income families with a refundable tax credit to help with their child-care expenses, and encourage flexible work schedules.",
  [["Support Working Families", "", []],
   ["Strengthen Our Schools", "", []],
   ["Help American Families Stay Healthy", "", []],
   ["Protect Homeownership", "", []],
   ["Strengthen Families at Home", "", []],
   ["Strengthen Retirement Security", "", []]]],
 ["Fiscal",
  "**Barack Obama will restore fiscal discipline to Washington:** Obama and Biden review the federal budget line by line and eliminate programs that t work or are unnecessary.don\n\n**Reverse Bush tax cuts for the wealthy:** Obama and Biden will protect tax cuts for poor and middle-class families, and will reverse most of the Bush tax cuts for the wealthiest taxpayers.\n\n**Close special interest corporate loopholes:** Obama and Biden will level the playing field for all businesses by eliminating special-interest loopholes and deductions, such as those for the oil and gas industry.",
  [["Restore Fiscal Discipline to Washington", "", []],
   ["Make the Tax System More Fair and Efficient", "", []]]],
 ["Foreign Policy",
  "**Secure loose nuclear materials from terrorists:** Obama and Biden will secure all loose nuclear materials in the world within four years, and will negotiate a verifiable global ban on the production of new nuclear weapons material to curb the spread of nuclear weapons.\n\n**Barack Obama will pursue tough, direct diplomacy without preconditions to end the threat from Iran:** Obama and Biden will present the Iranian regime with a clear choice. If Iran abandons its nuclear program and support for terrorism, they would offer incentives like membership in the World Trade Organization. If Iran continues its troubling behavior, Obama and Biden will step up our economic pressure and political isolation.\n\n**Renew American diplomacy:** Obama and Biden will renew American diplomacy to meet the challenges of the 21st century. They will rebuild our alliances. And they would be willing to meet with all nations, friend and foe, to advance American interests.",
  [["Ending the War in Iraq", "", []],
   ["Iran", "", []],
   ["Renewing American Diplomacy", "", []],
   ["Nuclear Weapons", "", []],
   ["Bipartisanship and Openness", "", []],
   ["On Israel", "", []],
   ["Meeting the Challenge of a Resurgent Russia", "", []],
   ["On Africa", "", []],
   ["On Latin America & the Caribbean", "", []],
   ["Learn More About the Obama-Biden Plan", "", []]]],
 ["Healthcare",
  "**Barack Obama will make health insurance affordable and accessible to all:** The Obama-Biden plan provides affordable, accessible health care for all Americans, builds on the existing healthcare system, and uses existing providers, doctors and plans to implement the plan.\n\n**Obama will lower health care costs:** The Obama plan will lower health care costs by $2,500 for a typical family by investing in health information technology, prevention and care coordination.\n\n**Promote public health:** Obama and Biden will require coverage of preventive services, including cancer screenings, and will increase state and local preparedness for terrorist attacks and natural disasters.",
  [["Make Health Insurance Work for People and Businesses - Not Just Insurance and Drug Companies.",
    "",
    []],
   ["Reduce Costs and Save a Typical American Family up to $2,500", "", []]]],
 ["Homeland Security",
  "**Barack Obama will defeat terrorism worldwide:** Obama and Biden will find, disrupt, and destroy al Qaeda; prepare the military to meet 21st century threats; and the Battle of  by ensuring American foreign policy is consistent with America's traditional values.Ideaswin \n\n**Prevent nuclear terrorism:** Obama and Biden will lead the effort to secure nuclear weapons materials at vulnerable sites within four years and help our allies stop the smuggling of weapons of mass destruction.\n\n**Strengthen American biosecurity:** Obama and Biden will work to prevent bioterror attacks and mitigate consequences by improving U.S. intelligence collection and response management.",
  [["Defeat Terrorism Worldwide", "", []],
   ["Prevent Nuclear Terrorism", "", []],
   ["Strengthen American Biosecurity", "", []],
   ["Protect Our Information Networks", "", []],
   ["Improve Intelligence Capacity and Protect Civil Liberties", "", []],
   ["Protect Americans from Terrorist Attacks and National Disasters", "", []],
   ["Protect Critical Infrastructure", "", []],
   ["Modernize America's Aging Infrastructure", "", []]]],
 ["Immigration",
  "**Barack Obama will secure our borders:** Obama and Biden want to preserve the integrity of our borders. They support additional personnel, infrastructure, and technology on the border and at our ports of entry.\n\n**Improve our immigration system:** Obama and Biden believe we must fix the dysfunctional immigration bureaucracy and increase the number of legal immigrants to keep families together and meet the demand for jobs that employers cannot fill.\n\n**Bring people out of the shadows:** Obama and Biden support a system that requires undocumented immigrants who are in good standing to pay a fine, learn English, and go to the back of the line for the opportunity to become citizens.",
  [["Create Secure Borders", "", []],
   ["Improve Our Immigration System", "", []],
   ["Remove Incentives to Enter Illegally", "", []],
   ["Bring People Out of the Shadows", "", []],
   ["Work with Mexico", "", []]]],
 ["Iraq",
  "**Barack Obama will responsibly end the war in Iraq: ** Immediately upon taking office, Obama will give his Secretary of Defense and military commanders a new mission in Iraq: successfully ending the war. The removal of our troops will be responsible and phased.\n\n**Encourage political accommodation:** Obama and Biden will press Iraq's leaders to take responsibility for their future and to substantially spend their oil revenues on their own reconstruction.\n\n**Increase stability in Iraq and the region:** Obama and Biden will launch an aggressive diplomatic effort to reach a comprehensive compact on the stability of Iraq and the region. They also will address Iraq's refugee crisis.",
  [["Create Secure Borders", "", []],
   ["Improve Our Immigration System", "", []],
   ["Remove Incentives to Enter Illegally", "", []],
   ["Bring People Out of the Shadows", "", []],
   ["Work with Mexico", "", []]]],
 ["Poverty",
  "**Barack Obama will expand access to jobs:** Obama and Biden will invest $1 billion over five years in transitional jobs and career pathway programs that implement proven methods of helping low-income Americans succeed in the workforce.\n\n**Make work pay for all Americans:** Obama and Biden will increase benefits for working parents, raise the minimum wage to $9.50 an hour by 2011, and provide tax relief to low- and middle-income workers.\n\n**Support rural and urban areas:** Obama and Biden will invest in rural small businesses, improve rural schools, and attract more doctors to rural areas. And they will work with urban leaders to increase the supply of affordable housing and address the unique challenges of every metropolitan area.",
  [["Expand Access to Jobs", "", []],
   ["Make Work Pay for All Americans", "", []],
   ["Strengthen Families", "", []],
   ["Increase the Supply of Affordable Housing", "", []],
   ["Tackle Concentrated Poverty", "", []]]],
 ["Rural",
  "**Barack Obama will ensure economic opportunity for family farmers:** Obama and Biden will fight for farm programs that provide family farmers with stability and predictability. They will implement a $250,000 payment limitation so that we help family farmers - not large corporate agribusiness.\n\n**Support small business development:** Obama and Biden will provide capital for farmers to create value-added enterprises, like cooperative marketing initiatives and farmer-owned processing plants.\n\n**Improve rural quality of life:** Obama and Biden will combat methamphetamine use, improve health care, improve education, and upgrade infrastructure in rural areas.",
  [["Ensure Economic Opportunity For Family Farmers", "", []],
   ["Support Rural Economic Development", "", []],
   ["Improve Rural Quality Of Life", "", []]]],
 ["Service",
  "**Barack Obama will enable all Americans to serve:** Obama and Biden will expand AmeriCorps and the Peace Corps, engage retiring Americans, and set up an America's Voice Initiative to send Americans who are fluent speakers of local languages to expand our public diplomacy.\n\n**Integrate service into learning:** Obama and Biden will set a goal that all middle and high school students do 50 hours of community service a year, and will establish a new tax credit that is worth $4,000 a year in exchange for 100 hours of public service a year.\n\n**Invest in the nonprofit sector:** Obama and Biden will create a Social Investment Fund Network to use federal seed money to leverage private sector funding. They will create an agency dedicated to building the capacity and effectiveness of the nonprofit sector.",
  [["Enable All Americans to Serve", "", []],
   ["Integrate Service into Learning", "", []],
   ["Invest in the Nonprofit Sector", "", []]]],
 ["Seniors & Social Security",
  "**Barack Obama will protect Social Security:** Obama and Biden are committed to ensuring Social Security is solvent and viable for the American people, now and in the future. They are strongly opposed to privatizing Social Security.\n\n**Provide cheaper prescription drugs:** Obama and Biden will allow the federal government to negotiate for lower drug prices for the Medicare program. They also support allowing seniors to import safe prescription drugs from overseas.\n\n**Protect and strengthen Medicare:** Obama and Biden are committed to the long-term strength of the Medicare program. They will reduce waste in the Medicare system and will tackle fundamental healthcare reform.",
  [["Protect Social Security", "", []],
   ["Strengthen Retirement Savings", "", []],
   ["Affordable Health Care", "", []],
   ["Protect and Honor Seniors", "", []]]],
 ["Taxes",
  "Barack Obama's tax plan delivers broad-based tax relief to middle class families and cuts taxes for small businesses and companies that create jobs in America, while restoring fairness to our tax code and returning to fiscal responsibility. Coupled with Obama's commitment to invest in key areas like health, clean energy, innovation and education, his tax plan will help restore bottom-up economic growth that helps create good jobs in America and empowers all families achieve the American dream.",
  []],
 ["Technology",
  "**Barack Obama will protect the openness of the internet:** Obama and Biden strongly support the principle of network neutrality to preserve the benefits of open competition on the Internet.\n\n**Deploy a modern communications infrastructure:** Obama and Biden believe we can get true broadband to every community in America.\nImprove America's competitiveness:\n\nObama and Biden will ensure our goods and services are treated fairly in foreign markets, invest in the sciences, and will provide new research grants to the most outstanding early-career researchers in the country.",
  [["Ensure an open Internet.", "", []],
   ["Create a transparent and connected democracy.", "", []],
   ["Encourage a modern communications infrastructure.", "", []],
   ["Prepare all of our children for a 21st century economy.", "", []],
   ["Improve America's competitiveness.", "", []],
   ["Employ science and technology to solve our nation's most pressing problems.",
    "",
    []]]],
 ["Urban Policy",
  "**Barack Obama will strengthen federal commitment to our cities:** Obama and Biden will create a White House Office of Urban Policy to develop a strategy for metropolitan America and to ensure that all federal dollars targeted to urban areas are effectively spent on the highest-impact programs.\n\n**Stimulate economic prosperity in urban areas:** Obama and Biden will support job creation, enhance workforce training, and increase access to capital for underserved businesses.\n\n**Make housing more affordable:** Obama and Biden will ensure that middle-class Americans get the financial assistance they need to purchase or keep their own home. And they will increase the supply of affordable housing.",
  [["Strengthen Federal Commitment to our Cities", "", []],
   ["Stimulate Economic Prosperity in our Metropolitan Regions", "", []],
   ["Housing", "", []],
   ["Poverty", "", []],
   ["Strengthen Livability of Cities", "", []],
   ["Urban Education", "", []],
   ["Crime and Law Enforcement", "", []],
   ["Strengthen Homeland Security", "", []],
   ["Support Families", "", []]]],
 ["Veterans",
  "**Barack Obama will restore our sacred trust with our nation's veterans:** Obama and Biden are committed to creating a 21st Century Department of Veterans' Affairs that provides the care and benefits our nation's veterans deserve.\n\n**Help returning service members:** Obama and Biden will improve the quality of health care for veterans, rebuild the VA's broken benefits system, and combat homelessness among veterans.\n\n**Improve mental health treatment:** Obama and Biden will improve mental health treatment for troops and veterans suffering from combat-related psychological injuries.",
  []],
 ["Women", "", []],
 ["Additional Issues",
  "",
  [["Arts", "", []],
   ["Child Advocacy", "", []],
   ["Katrina", "", []],
   ["Science", "", []],
   ["Sportsmen", "", []],
   ["Transportation", "", []]]]]

namespace :app do
  task :bootstrap => [:environment] do
    
  end
  
  task :seed => [:environment] do
    
  end
  
  task :setup => [:bootstrap, :seed]
end