global:
  project_name: tabsonobama
  
development: &non_production_settings
  site_url: http://localhost:3000
  site_name: Tabs on Obama
  admin_email: tabsonobama@gmail.com
  
test:
  <<: *non_production_settings

staging:
  site_url: http://tabsonobama.org
  site_name: Tabs on Obama
  admin_email: chirag@tabsonobama.org
  
production:
  site_url: http://tabsonobama.org
  site_name: Tabs on Obama
  admin_email: chirag@tabsonobama.org
