global:
  project_name: tabsonrahm
  
development: &non_production_settings
  root_controller: splashes
  site_url: http://localhost:3000
  site_name: Tabs on Obama
  admin_email: tabsonobama@gmail.com
  
test:
  <<: *non_production_settings

staging:
  root_controller: splashes
  site_url: http://staging.tabsonobama.org
  site_name: Tabs on Obama
  admin_email: chirag@tabsonobama.org
  
production:
  root_controller: splashes
  site_url: http://www.tabsonrahm.org
  site_name: Tabs on Obama
  admin_email: chirag@tabsonobama.org
