global:
  project_name: tabsonrahm
  
development: &non_production_settings
  root_controller: home
  site_url: http://localhost:3000
  site_name: Tabs on Rahm
  admin_email: chirag@tabsonrahm.org
  
test:
  <<: *non_production_settings

staging:
  root_controller: home
  site_url: http://staging.tabsonrahm.org
  site_name: Tabs on Rahm
  admin_email: chirag@tabsonrahm.org
  
production:
  root_controller: splashes
  site_url: http://www.tabsonrahm.org
  site_name: Tabs on Rahm
  admin_email: chirag@tabsonrahm.org
